version: 2
jobs:
  build_and_test:
    working_directory: ~/project
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore Npm Package Cache
          keys:
            - npm-packages-v1
      - run:
          name: Packager Version
          command: npm --version
      - run:
          name: Install Dependencies
          command: NODE_ENV=development npm install && npm run prepare
      - save_cache:
          name: Save Npm Package Cache
          key: npm-packages-v1
          paths:
            - node_modules/
      - run:
          name: Lint sources
          command: npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
